name: curtyowell
favicon: null
layout_spectrum: 0.5443534669466317
typography_spectrum: 0.9217842135112733
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9007092691026628
  lightness: 0.6713727205060422
  saturation: 0.22182536427862942
  rhythmicContrast: 0.4495514191221446
purpose: []
